python3 -m spacy download en_core_web_lg
python3 -m spacy download en_core_web_md
python3 -m spacy download en_core_web_sm
python3 -m spacy download it_core_news_sm
python3 -m spacy download de_core_news_sm
python3 -m spacy download fr_core_news_sm
python3 -m spacy download fr_core_news_md
python3 -m spacy download es_core_news_sm
python3 -m spacy download es_core_news_md
python3 -m spacy download nl_core_news_sm
